database:
  type: 'sqlite' # 'sqlite' or 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'

afelium:
  # Price in coins to buy 1 afelium
  buy: 10000
  # Coins received per afelium selled
  sell: 5000