database:
  version: '1.1.4'
  type: 'sqlite' # 'sqlite' or 'mysql'
  mysql:
    address: 'localhost:3306'
    username: 'root'
    password: ''
    database: 'test'
  sqlite:
    file: 'database/database.db'